### ISSUE TITLE
Apply page - split text into paragraphs

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#37]
Adjust the text on the apply page in separate paragraphs, see image below

<img width="754" alt="screenshot 2018-10-23 at 10 30 04" src="https://user-images.githubusercontent.com/20355307/47347022-a96dd080-d6ae-11e8-99ce-240c2473c2fc.png">

**Comment by bhawna333** [comment]
Can look into this as well.

**Comment by lustoykov** [comment]
it's yours! ;-)

**Comment by BastianRieder** [comment]
Here you can copy the text:

You can be the best graduate of all time, but when you go to your first job after uni, you're a newbie. Maybe you have heard that modern tech companies nowadays work in "agile teams" and no longer in departments and divisions. 
Instead of top-down management, there are flat hierarchies and that the teams organize themselves and their projects on their own. 
You also might have heard about "agile", "Scrum" and "Design Thinking". But what's that in reality? How does it work in the real world?
